ENGINES = {
    "ahmia": "http://msydqstlz2kzerdg.onion",
    "torch": "http://xmh57jrzrnw6insl.onion",
    "darksearchio": "http://darksearch.io",
    "onionland": "http://3bbad7fauom4d6sgppalyqddsqbf5u5p56b5k5uk2zxsy3d6ey2jobad.onion",
    "notevil": "http://hss3uro2hsxfogfq.onion",
    "visitor": "http://visitorfi5kl7q7i.onion",
    "darksearchenginer": "http://7pwy57iklvt6lyhe.onion",
    "phobos": "http://phobosxilamwcg75xt22id7aywkzol6q6rfl2flipcqoc4e4ahima5id.onion",
    "onionsearchserver": "http://oss7wrm7xvoub77o.onion",
    "grams": "http://grams7enqfy4nieo.onion",
    "grams1": "http://grams7ebnju7gwjl.onion",
    "candle": "http://gjobjn7ievumcq6z.onion",
    "torsearchengine": "http://searchcoaupi3csb.onion",
    "torsearchengine1": "http://searcherc3uwk535.onion",
    "torgle": "http://torglejzid2cyoqt.onion",
    "torgle1": "http://torgle5fj664v7pf.onion",
    "onionsearchengine": "http://onionf4j3fwqpeo5.onion",
    "tordex": "http://tordex7iie7z2wcg.onion",
    "tor66": "http://tor66sezptuu2nta.onion",
    "tormax": "http://tormaxunodsbvtgo.onion",
    "haystack": "http://haystakvxad7wbk5.onion",
    "multivac": "http://multivacigqzqqon.onion",
    "evosearch": "http://evo7no6twwwrm63c.onion",
    "oneirun": "http://oneirunda366dmfm.onion",
    "deeplink": "http://deeplinkdeatbml7.onion",
}
